import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LenisContext from "@/context/lenis-context";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-bridal-health">
      <body className={inter.className}>
        <LenisContext>
          <Header />
          {children}
        </LenisContext>
      </body>
    </html>
  );
}
